this fixes malformed sql for getIndexInfo
sqlite stopped throwing an exception on

    pragma index_list("table");

Which was causing the sql generated by the getIndexInfo method
to be corrupt.

java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (near
"1": syntax error)